const List<String> techStackOptions = [
  '.NET',
  '.NET Core',
  '.net',
  '2D Rendering',
  '3D Rendering',
  'AAC',
  'ABAP',
  'AI/인공지능',
  'AR',
  'ARM',
  'ASIC',
  'ASP.NET',
  'AWS',
  'AWS Amplify',
  'AWS App Mesh',
  'AWS Certificate Manager',
  'AWS Cloud Development Kit',
  'AWS CloudFormation',
  'AWS CloudHSM',
  'AWS CodeCommit',
  'AWS Copilot',
  'AWS Data Pipeline',
  'AWS DataOps Development Kit',
  'AWS Glue',
  'AWS IAM',
  'AWS IoT Device Management',
  'AWS Lambda',
  'AWS Step Functions',
  'AWS WAF',
  'AZURE',
  'Active Directory',
  'ActiveMQ',
  'Adobe Illustrator',
  'Adobe Photoshop',
  'Adobe XD',
  'Airflow',
  'Ajax',
  'Amazon Athena',
  'Amazon CloudFront',
  'Amazon DynamoDB',
  'Amazon EC2',
  'Amazon EC2 Container Service',
  'Amazon EKS',
  'Amazon ElastiCache',
  'Amazon Kinesis',
  'Amazon Quicksight',
  'Amazon RDS',
  'Amazon RDS for PostgreSQL',
  'Amazon Route 53',
  'Amazon S3',
  'Amazon SageMaker',
  'Analog',
  'Android OS',
  'Android SDK',
  'Android Studio',
  'Angular',
  'Angular 2',
  'AngularJS',
  'Ansible',
  'Ant Design',
  'Apache HTTP Server',
  'Apache Mesos',
  'Apache RocketMQ',
  'Apache Spark',
  'Apache Tomcat',
  'Apex',
  'ApexCharts',
  'Apollo',
  'Appium',
  'ArangoDB',
  'Arduino',
  'Argo',
  'Asana',
  'Auth0',
  'Autocad',
  'Azure App Service',
  'Azure Application Insights',
  'Azure CDN',
  'Azure DevOps',
  'Azure DevOps Server',
  'Azure IoT Hub',
  'Azure SQL Database',
  'Azure Storage',
  'Azure Synapse',
  'Babel',
  'Backpack',
  'Backendless',
  'Bamboo',
  'BigData',
  'Bitbucket',
  'Blazor',
  'Blender',
  'Blockchain',
  'Bootstrap',
  'C',
  'C#',
  'C++',
  'C++ Builder',
  'CISA',
  'CISSP',
  'CImg',
  'CMake',
  'COBOL',
  'CPPG',
  'CSS 3',
  'CSS Modules',
  'CUDA',
  'Cachet',
  'Caffe2',
  'Cassandra',
  'Ccna',
  'Ccnp',
  'Celery',
  'CentOS',
  'Chart.js',
  'Charted',
  'Chef',
  'CircleCI',
  'Cisco',
  'Cisco ISE',
  'Citrix Gateway',
  'Classic ASP',
  'ClickUp',
  'Closure Compiler',
  'Cloud AI Platform Pipelines',
  'Cloud CMS',
  'CloudBees',
  'CloudFlare',
  'CodeIgniter',
  'CodePush',
  'Composer',
  'Confluence',
  'Confluent',
  'Coqui TTS',
  'Create React Native App',
  'CrossBrowserTesting',
  'D3.js',
  'DB',
  'DC/OS',
  'DICOM',
  'Dart',
  'DataGrip',
  'Datadog',
  'Debezium',
  'DeepLearning',
  'Defi',
  'Delphi',
  'Deta Cloud',
  'DevDocs',
  'DirectX',
  'Django',
  'Django REST framework',
  'Docker',
  'Docker Compose',
  'Docker Swarm',
  'Dockerized',
  'Druid',
  'Dw',
  'Dynamo',
  'EDA',
  'ELK',
  'ERP',
  'ES6',
  'Eclipse',
  'EditorConfig',
  'Elastic Apache Mesos',
  'Elasticsearch',
  'Electron',
  'Embedded',
  'Embedded Linux',
  'Emotion',
  'Etl',
  'Express',
  'ExpressJS',
  'FFMPEG',
  'FPGA',
  'FW',
  'FastAPI',
  'Figma',
  'Firebase',
  'Firebase Hosting',
  'Firewall',
  'Flask',
  'Flow',
  'Flutter',
  'Fusion 360',
  'GCP',
  'GNU Bash',
  'GUI',
  'Gensim',
  'Git',
  'Git Flow',
  'GitHub',
  'GitHub Actions',
  'GitHub Copilot',
  'GitLab',
  'GitLab CI',
  'Go',
  'GoLand',
  'Golang',
  'Google AI Platform',
  'Google Analytics',
  'Google BigQuery Data Transfer Service',
  'Google Cloud IoT Core',
  'Google Cloud Platform',
  'Google Docs',
  'Google Drive',
  'Gradle',
  'Grafana',
  'GraphQL',
  'GrapheneDB',
  'Groovy',
  'HALCON',
  'HAProxy',
  'HTML5',
  'HTTPie',
  'HW',
  'Hadoop',
  'Hasura',
  'Helm',
  'Heroku',
  'Hibernate',
  'Hive',
  'Hyperledger Indy',
  'IBM Containers',
  'IPS',
  'ISMS',
  'Insight',
  'Infra',
  'IntelliJ IDEA',
  'Istio',
  'JSON',
  'JSON Web Token',
  'JSON-RPC',
  'JSP',
  'JUnit',
  'Java',
  'JavaScript',
  'Jenkins',
  'Jest',
  'Jetpack',
  'Jira',
  'Jotai',
  'Jupyter',
  'K8S',
  'Kafka',
  'Kanban Tool',
  'Keras',
  'Kibana',
  'Kotlin',
  'Ktor',
  'Kubeflow',
  'Kubernetes',
  'L2',
  'L3',
  'L4',
  'L7',
  'Laravel',
  'Linear',
  'Linux',
  'LinuxKit',
  'Loki',
  'Looker',
  'LowCodeEngine',
  'MATLAB',
  'MCU',
  'MES',
  'MQTT',
  'MSA',
  'MSSQL',
  'MVVM',
  'MachineLearning',
  'Mantis',
  'MariaDB',
  'Markdown',
  'Memcached',
  'Mesosphere',
  'MessagePack',
  'Messenger Bot',
  'Metabase',
  'Mfc',
  'Microsoft Azure',
  'Microsoft Excel',
  'Microsoft Office 365',
  'Microsoft Outlook',
  'Microsoft Power Automate',
  'Microsoft PowerApps',
  'Microsoft SQL Server',
  'Microsoft SharePoint',
  'Microsoft Teams',
  'Milanote',
  'Minio',
  'Miplatform',
  'Mocha',
  'MongoDB',
  'MongoDB Atlas',
  'MySQL',
  'MySQL WorkBench',
  'Mybatis',
  'NGINX',
  'NLP',
  'NLTK',
  'Neo4j',
  'NestJS',
  'Netty',
  'Network',
  'Nexacro',
  'Next.js',
  'NoCodeAPI',
  'NoSql',
  'Node.js',
  'Notion',
  'Notion.so',
  'NumPy',
  'Nuxt.js',
  'OAuth2',
  'OLAP',
  'Objective-C',
  'Octane AI',
  'OpenAPI',
  'OpenCV',
  'OpenGL',
  'OpenSSL',
  'OpenStack',
  'Oracle',
  'Oracle Integration Cloud',
  'Oracle PL/SQL',
  'Orcad',
  'PCB',
  'PHP',
  'PLC',
  'Pads',
  'Pandas',
  'Perforce',
  'Perl',
  'Photon',
  'Pirsch Analytics',
  'Playwright',
  'PostgreSQL',
  'Postman',
  'PowerBI',
  'Presto',
  'Prisma',
  'Prometheus',
  'Protobuf',
  'Pulumi',
  'PyQt',
  'PySpark',
  'PyTorch',
  'Python',
  'QA',
  'QlikView',
  'Qrvey Analytics',
  'Qt',
  'QueryDSL',
  'Queue',
  'R',
  'RDB',
  'REST API',
  'RF',
  'ROS',
  'RPA',
  'RTOS',
  'RabbitMQ',
  'Rails',
  'Rancher',
  'React',
  'React Canvas',
  'React Hook Form',
  'React Native',
  'React Native Seed',
  'React Query',
  'React Router',
  'React.js Boilerplate',
  'ReactPHP',
  'Realm',
  'Recoil',
  'Redash',
  'Redis',
  'Redis Cloud',
  'Redmine',
  'Redux',
  'Retrofit',
  'Rollup',
  'Router',
  'Rust',
  'Rxswift',
  'SAP',
  'SCSS',
  'SMPS',
  'SPICE',
  'SQL',
  'SQLite',
  'STUDIO',
  'SW',
  'Salesforce',
  'Sass',
  'Scala',
  'Scikit-learn',
  'ScrapingBot',
  'SecureCRT',
  'Segment',
  'Selenium',
  'Semantic UI',
  'Semantic UI React',
  'Sentry',
  'Sequel',
  'Sequelize',
  'Serverless',
  'Shell',
  'Shopify',
  'SketchUp',
  'Slack',
  'Slim',
  'Snort',
  'Snowflake',
  'SocialTracker',
  'Socket.IO',
  'Solidity',
  'Solidworks',
  'SonarQube',
  'SpaCy',
  'Spark',
  'Splunk',
  'Spring',
  'Spring Batch',
  'Spring Boot',
  'Spring Data',
  'Spring Data JPA',
  'Spring Framework',
  'Spring MVC',
  'Spring Security',
  'Spring Tools 4',
  'Sprout Social',
  'Stack',
  'Storybook',
  'Struts2',
  'SummitDB',
  'Supabase',
  'Superset',
  'Swagger UI',
  'Swift',
  'Swift AI',
  'SwiftUI',
  'Switch',
  'TCP/IP',
  'Tableau',
  'TailwindCSS',
  'TensorFlow',
  'TensorFlow.js',
  'Terraform',
  'Tesseract OCR',
  'Testrail',
  'Thymeleaf',
  'Tibero',
  'Toolbox',
  'Transformers',
  'Trello',
  'TypeORM',
  'TypeScript',
  'Ubuntu',
  'Uniform CSS',
  'Unity',
  'Unreal Engine',
  'Utm',
  'VHDL',
  'VMware',
  'VMware vSphere',
  'VPN',
  'VR',
  'Vb.net',
  'Vercel',
  'Verilog',
  'Vertica',
  'Visual Basic',
  'Visual C++',
  'Visual Studio',
  'Visual Studio Code',
  'Vite',
  'Vue.js',
  'Vuex',
  'WCF',
  'WPF',
  'WebAssembly',
  'WebGL',
  'WebRTC',
  'WebSocket',
  'Webpack',
  'Windows',
  'Windows Server',
  'WordPress',
  'XML',
  'Xcode',
  'Xen',
  'Yarn',
  'Yocto',
  'Zabbix',
  'Zephyr',
  'Zeplin',
  'Zsh (Z shell)',
  'Zustand',
  'amazon dynamodb',
  'android os',
  'angularjs',
  'aws',
  'axios',
  'c',
  'c#',
  'c++',
  'css 3',
  'dart',
  'elasticsearch',
  'etcd',
  'ethernet',
  'fastlane',
  'firebase',
  'flutter',
  'gRPC',
  'graphql',
  'html5',
  'iOS',
  'ios',
  'jOOQ',
  'jQuery',
  'jQuery UI',
  'javascript',
  'labview',
  'macOS',
  'mobX',
  'mysql',
  'nosql',
  'pnpm',
  'postgresql',
  'pytest',
  'qt',
  'react',
  'react-testing-library',
  'redis',
  'redux-saga',
  'rest api',
  'rpa',
  'rxswift',
  'scikit-learn',
  'spring boot',
  'spring data jpa',
  'styled-components',
  'sw',
  'swift',
  'three.js',
  'vmware',
  'vue.js',
  'vuex',
  'wpf'
];
