version: '3.8'

services:
  backend:
    container_name: backend
    build:
      context: ../backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    networks:
      - app-network
      - s12p21c103_app-network

  fastapi:
    container_name: fastapi
    build:
      context: ../bigdata
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      APP_NAME: "gittowork"
      DEBUG: "true"
      MYSQL_URL: "mysql://c103:kOZmrcUmgnKl5FKBdBuj@mysql:3306/gittowork"
      MONGODB_URI: "mongodb://mongodb:27017/gittowork"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    networks:
      - app-network
      - s12p21c103_app-network

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../CI-CD/gittowork.conf:/etc/nginx/conf.d/gittowork.conf:ro
      - /etc/letsencrypt:/etc/nginx/ssl:ro
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    depends_on:
      - backend
      - fastapi
    networks:
      - app-network
      - s12p21c103_app-network

networks:
  app-network:
    driver: bridge
  s12p21c103_app-network:
    external: true
