version: '3.8'

services:
  backend:
    container_name: backend
    hostname: backend
    build:
      context: ../backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    networks:
      s12p21c103_app-network:
        aliases:
          - backend

  fastapi:
    container_name: fastapi
    hostname: fastapi
    build:
      context: ../bigdata
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      APP_NAME: "gittowork"
      DEBUG: "true"
      MYSQL_URL: "mysql://c103:kOZmrcUmgnKl5FKBdBuj@mysql:3306/gittowork"
      MONGODB_URI: "mongodb://mongodb:27017/gittowork"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    networks:
      s12p21c103_app-network:
        aliases:
          - fastapi

networks:
  s12p21c103_app-network:
    external: true
